package it.xyra.mamout.data.local

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a prompt header in the local database.
 *
 * @property id The unique identifier for the prompt, auto-generated by Room.
 * @property title The title of the prompt as shown in the UI.
 * @property description A brief summary or description of the prompt.
 */
@Entity(tableName = "prompts")
class PromptEntity (
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val title: String,
    val description: String
)